2021-01-25 18:13:53.779469: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2021-01-25 18:13:53.873671: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: TITAN X (Pascal) major: 6 minor: 1 memoryClockRate(GHz): 1.531
pciBusID: 0000:04:00.0
2021-01-25 18:13:53.873975: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2021-01-25 18:13:53.876301: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2021-01-25 18:13:53.878194: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2021-01-25 18:13:53.878613: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2021-01-25 18:13:53.881099: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2021-01-25 18:13:53.883014: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2021-01-25 18:13:53.888879: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2021-01-25 18:13:53.897304: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2021-01-25 18:13:53.897781: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2021-01-25 18:13:53.909001: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2099810000 Hz
2021-01-25 18:13:53.909383: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x561e6cefa390 executing computations on platform Host. Devices:
2021-01-25 18:13:53.909424: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2021-01-25 18:13:53.913729: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: TITAN X (Pascal) major: 6 minor: 1 memoryClockRate(GHz): 1.531
pciBusID: 0000:04:00.0
2021-01-25 18:13:53.913772: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2021-01-25 18:13:53.913795: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2021-01-25 18:13:53.913814: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2021-01-25 18:13:53.913834: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2021-01-25 18:13:53.913853: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2021-01-25 18:13:53.913873: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2021-01-25 18:13:53.913892: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2021-01-25 18:13:53.921959: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2021-01-25 18:13:53.922009: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2021-01-25 18:13:54.154681: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-01-25 18:13:54.154732: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2021-01-25 18:13:54.154740: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2021-01-25 18:13:54.165976: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11448 MB memory) -> physical GPU (device: 0, name: TITAN X (Pascal), pci bus id: 0000:04:00.0, compute capability: 6.1)
2021-01-25 18:13:54.170862: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x561e6d544e50 executing computations on platform CUDA. Devices:
2021-01-25 18:13:54.170883: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): TITAN X (Pascal), Compute Capability 6.1
2021-01-25 18:14:00.477977: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2021-01-25 18:14:00.683152: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2021-01-25 18:15:26.761484: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at summary_kernels.cc:106 : Unknown: The events file /home/ramon/work/mcv3/outs/2/train/events.out.tfevents.1611594839.etse-75-51.7709.4251.v2 has disappeared.
	Failed to flush 2 events to /home/ramon/work/mcv3/outs/2/train/events.out.tfevents.1611594839.etse-75-51.7709.4251.v2
	Could not flush events file.
Using TensorFlow backend.
w4code_example.py:51: UserWarning: Update your `Model` call to the Keras 2 API: `Model(inputs=Tensor("in..., outputs=Tensor("pr...)`
  model = Model(input=base_model.input, output=x)
w4code_example.py:99: UserWarning: The semantics of the Keras 2 argument `steps_per_epoch` is not the same as the Keras 1 argument `samples_per_epoch`. `steps_per_epoch` is the number of batches to draw from the generator at each epoch. Basically steps_per_epoch = samples_per_epoch/batch_size. Similarly `nb_val_samples`->`validation_steps` and `val_samples`->`steps` arguments have changed. Update your method calls accordingly.
  validation_steps= (int(validation_samples//batch_size)+1), callbacks=[tbCallBack])
w4code_example.py:99: UserWarning: Update your `fit_generator` call to the Keras 2 API: `fit_generator(<keras.pre..., steps_per_epoch=13, validation_data=<keras.pre..., validation_steps=26, callbacks=[<keras.ca..., epochs=20)`
  validation_steps= (int(validation_samples//batch_size)+1), callbacks=[tbCallBack])
Traceback (most recent call last):
  File "w4code_example.py", line 99, in <module>
    validation_steps= (int(validation_samples//batch_size)+1), callbacks=[tbCallBack])
  File "/home/ramon/anaconda3/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/ramon/anaconda3/lib/python3.7/site-packages/keras/engine/training.py", line 1732, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/ramon/anaconda3/lib/python3.7/site-packages/keras/engine/training_generator.py", line 260, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/ramon/anaconda3/lib/python3.7/site-packages/keras/callbacks/callbacks.py", line 152, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/ramon/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/callbacks.py", line 1611, in on_epoch_end
    self._log_metrics(logs, prefix='epoch_', step=step)
  File "/home/ramon/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/callbacks.py", line 1681, in _log_metrics
    summary_ops_v2.scalar(name, value, step=step)
  File "/home/ramon/anaconda3/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home/ramon/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/summary_ops_v2.py", line 239, in as_default
    self.flush()
  File "/home/ramon/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/summary_ops_v2.py", line 256, in flush
    return _flush_fn(writer=self)
  File "/home/ramon/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/summary_ops_v2.py", line 932, in flush
    return gen_summary_ops.flush_summary_writer(resource, name=name)
  File "/home/ramon/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_summary_ops.py", line 257, in flush_summary_writer
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnknownError: The events file /home/ramon/work/mcv3/outs/2/train/events.out.tfevents.1611594839.etse-75-51.7709.4251.v2 has disappeared.
	Failed to flush 2 events to /home/ramon/work/mcv3/outs/2/train/events.out.tfevents.1611594839.etse-75-51.7709.4251.v2
	Could not flush events file. [Op:FlushSummaryWriter]
